# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PycharmProjects\handle_oracle\oracle_query.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1065, 782)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_2.setStyleSheet("font: 10pt \"微软雅黑\";\n"
"color: rgb(255, 85, 0);")
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 1, 0, 1, 2)
        self.checkBox = QtWidgets.QCheckBox(self.tab)
        self.checkBox.setStyleSheet("font: 10pt \"黑体\";\n"
"selection-color: rgb(85, 170, 0);")
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 2, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setAutoFillBackground(True)
        self.label.setStyleSheet("font: 11pt \"黑体\";")
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 4, 0, 1, 1)
        self.filepath = QtWidgets.QLineEdit(self.tab)
        self.filepath.setObjectName("filepath")
        self.gridLayout.addWidget(self.filepath, 3, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(75, 0))
        self.pushButton.setStyleSheet("font: 10pt \"黑体\";\n"
"background-color: rgb(85, 170, 127);")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setAutoFillBackground(True)
        self.label_5.setStyleSheet("font: 11pt \"黑体\";")
        self.label_5.setTextFormat(QtCore.Qt.PlainText)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 3, 1, 1, QtCore.Qt.AlignRight)
        self.tableView_2 = QtWidgets.QTableView(self.tab)
        self.tableView_2.setObjectName("tableView_2")
        self.gridLayout.addWidget(self.tableView_2, 5, 3, 1, 2)
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 1, 2, 2, 1)
        self.tableView = QtWidgets.QTableView(self.tab)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 5, 0, 1, 3)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setAutoFillBackground(True)
        self.label_4.setStyleSheet("font: 11pt \"黑体\";")
        self.label_4.setTextFormat(QtCore.Qt.PlainText)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 3, 1, 1, QtCore.Qt.AlignRight)
        self.lcdNumber = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber.setMinimumSize(QtCore.QSize(125, 68))
        self.lcdNumber.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 0, 4, 2, 1)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber_2.setMinimumSize(QtCore.QSize(125, 84))
        self.lcdNumber_2.setStyleSheet("font: 10pt \"黑体\";\n"
"background-color: rgb(85, 170, 127);")
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.gridLayout.addWidget(self.lcdNumber_2, 2, 4, 3, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableView_3 = QtWidgets.QTableView(self.groupBox_3)
        self.tableView_3.setObjectName("tableView_3")
        self.gridLayout_3.addWidget(self.tableView_3, 1, 0, 1, 1)
        self.tableView_4 = QtWidgets.QTableView(self.groupBox_3)
        self.tableView_4.setObjectName("tableView_4")
        self.gridLayout_3.addWidget(self.tableView_4, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.gridLayout_4.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_4.addWidget(self.pushButton_4, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1065, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.pushButton.clicked.connect(MainWindow.sql_query)
        self.pushButton_3.clicked.connect(MainWindow.open_file)
        self.pushButton_2.clicked.connect(MainWindow.output_excel)
        self.pushButton_4.clicked.connect(MainWindow.handle_item_excel)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox_2.setText(_translate("MainWindow", "查询sys_indicate_data"))
        self.checkBox.setText(_translate("MainWindow", "模糊查询(只支持单行)"))
        self.label.setToolTip(_translate("MainWindow", "<html><head/><body><p> 多行支持, 参数可以是MRID,NAME,IRN 默认查询identifyobject</p></body></html>"))
        self.label.setText(_translate("MainWindow", "输入查询条件"))
        self.pushButton_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>输出结果到本地</p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "输出EXCEL"))
        self.pushButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>查询数据库</p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "查询"))
        self.pushButton_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>查询数据库</p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "打开EXCEL"))
        self.label_5.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "成功返回条数"))
        self.label_4.setText(_translate("MainWindow", "查询条数"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "查询"))
        self.groupBox_3.setTitle(_translate("MainWindow", "指标对照表"))
        self.label_2.setText(_translate("MainWindow", "电厂编码"))
        self.label_3.setText(_translate("MainWindow", "分类编码"))
        self.pushButton_4.setText(_translate("MainWindow", "加载"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "长源指标对照表"))

